services:
  cppm:
    build: .
    container_name: cppm_container
    platform: linux/amd64
    ports:
      - "8080:8080"
    volumes:
      - .:/app
    entrypoint: ""
    command: sleep infinity
  mlflow:
    build: 
      context: .
      dockerfile: mlflow.Dockerfile
    platform: linux/amd64
    volumes:
      - mlflow:/mlflow
    command: mlflow server --host 0.0.0.0 --port 5000 --backend-store-uri /mlflow --default-artifact-root /mlflow
    ports:
      - 9000:5000
volumes:
  mlflow: