channels:
- conda-forge
dependencies:
- python=3.12.11
- pip<=25.2
- pip:
  - mlflow==3.3.2
  - cloudpickle==3.1.1
  - defusedxml==0.7.1
  - matplotlib==3.10.5
  - numpy==2.2.6
  - pandas==2.3.2
  - psutil==7.0.0
  - pyarrow==21.0.0
  - scikit-learn==1.7.1
  - scipy==1.16.1
name: mlflow-env
