# Name of this workflow
name: Build-Test

# Name of this run
run-name: ${{ github.actor }} Building and Testing

# When this action will be triggered
on:
  push:
    tags:
      - 'v*'

jobs:
  build-test:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: app

    steps:
      - uses: actions/checkout@v4

      - name: Make envfile
        uses: SpicyPizza/create-envfile@v2.0
        with:
          envkey_MLFLOW_USERNAME: ${{ secrets.MLFLOW_USERNAME }}
          envkey_MLFLOW_PASSWORD: ${{ secrets.MLFLOW_PASSWORD }}
          envkey_MLFLOW_TRACKING_URI: ${{ secrets.MLFLOW_TRACKING_HOST }}
          envkey_MODEL_NAME: ${{ secrets.MODEL_NAME }}
          file_name: .env
          fail_on_empty: true
          sort_keys: true

      - name: Build the Docker image
        run: docker compose build

      - name: Compose up
        run: docker compose up -d
      - name: Testing
        run: docker compose exec -T cppm .venv/bin/pytest --ignore=app.py -v

      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Docker meta
        id: meta
        uses: docker/metadata-action@v5
        with:
          images: mastersubhajit/cppm-app
          tags: type=semver,pattern={{raw}}

      - name: Build and push
        uses: docker/build-push-action@v5
        with:
          context: .
          file: .Dockerfile
          push: true
          tags: ${{ steps.meta.outputs.tags }}

  deploy:
    environment: Production
    needs: build-test
    runs-on: ubuntu-latest
    steps:
      - name: SSH Remote Commands
        uses: appleboy/ssh-action@v1.0.0
        with:
          host: ${{ vars.HOST }}
          username: ${{ secrets.USERNAME }}
          key: ${{ secrets.KEY }}
          proxy_host: ${{ vars.PROXY_HOST }}
          proxy_username: ${{ secrets.USERNAME }}
          proxy_key: ${{ secrets.KEY }}
          script: |
            tag=${{ github.ref_name }} docker compose -f st125998/docker-compose.yml down
            tag=${{ github.ref_name }} docker compose -f st125998/docker-compose.yml up -d
